{
    "openapi": "3.0.0",
    "info": {
        "title": "Book API swagger documentation",
        "description": "This is a documentation for Book API",
        "termsOfService": "http:\\/\\/swagger.io\\/terms\\/",
        "contact": {
            "email": "wehbihazem@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http:\\/\\/www.apache.org\\/licenses\\/LICENSE-2.0.html"
        },
        "version": "1.0.0"
    },
    "components": {
        "responses": {
            "200": {
                "description": "Success getting data",
                "content": {
                    "application/json": {
                        "schema": {},
                        "example": {
                            "status": 200,
                            "success": true,
                            "message": "Author retrieved successfully",
                            "errors": null,
                            "data": {
                                "current_page": 1,
                                "data": [
                                    {
                                        "id": 5,
                                        "name": "Fujiko F Fujio",
                                        "created_at": "2020-02-15 11:58:35",
                                        "updated_at": "2020-02-15 11:58:35"
                                    },
                                    {
                                        "id": 2,
                                        "name": "Takeshi Maekawa",
                                        "created_at": "2020-02-11 22:23:33",
                                        "updated_at": "2020-02-11 22:23:35"
                                    },
                                    {
                                        "id": 1,
                                        "name": "Masashi Ueda",
                                        "created_at": "2020-02-11 22:23:08",
                                        "updated_at": "2020-02-15 10:48:35"
                                    }
                                ],
                                "first_page_url": "http:\\/\\/localhost:8000\\/api\\/v1\\/author?page=1",
                                "from": 1,
                                "last_page": 1,
                                "last_page_url": "http:\\/\\/localhost:8000\\/api\\/v1\\/author?page=1",
                                "next_page_url": null,
                                "path": "http:\\/\\/localhost:8000\\/api\\/v1\\/author",
                                "per_page": "15",
                                "prev_page_url": null,
                                "to": 3,
                                "total": 3
                            }
                        }
                    }
                }
            },
            "400": {
                "description": "Invalid request data",
                "content": {
                    "application/json": {
                        "schema": {},
                        "example": {
                            "status": 400,
                            "success": false,
                            "message": "There's something wrong with your request",
                            "errors": {
                                "name": [
                                    "The name field is required."
                                ]
                            },
                            "data": null
                        }
                    }
                }
            },
            "404": {
                "description": "Data not found",
                "content": {
                    "application/json": {
                        "schema": {},
                        "example": {
                            "status": 404,
                            "success": false,
                            "message": "Author not found",
                            "errors": null,
                            "data": null
                        }
                    }
                }
            }
        },
        "parameters": {
            "search": {
                "name": "search",
                "in": "query",
                "description": "Search by name",
                "schema": {
                    "type": "string"
                }
            },
            "order_by": {
                "name": "order_by",
                "in": "query",
                "description": "Order by column",
                "schema": {
                    "type": "string"
                }
            },
            "sort": {
                "name": "sort",
                "in": "query",
                "description": "Sort by asc/desc",
                "schema": {
                    "type": "string"
                }
            },
            "is_paginate": {
                "name": "is_paginate",
                "in": "query",
                "description": "Paginate the data",
                "schema": {
                    "type": "string",
                    "default": "true",
                    "enum": [
                        "true",
                        "false"
                    ]
                }
            },
            "per_page": {
                "name": "per_page",
                "in": "query",
                "description": "Limit data per page",
                "schema": {
                    "type": "string",
                    "default": "15"
                }
            },
            "select_field": {
                "name": "select_field",
                "in": "query",
                "description": "Selected column of the data",
                "schema": {
                    "type": "string"
                }
            },
            "id": {
                "name": "id",
                "in": "path",
                "description": "Author ID",
                "required": true,
                "schema": {
                    "type": "integer",
                    "format": "int64"
                }
            }
        },
        "requestBodies": {
            "Author": {
                "description": "Author object that needs to be added to the body",
                "required": true,
                "content": {
                    "application/json": {
                        "schema": {},
                        "example": {
                            "name": "Fujiko F Fujio"
                        }
                    }
                }
            },
            "Book": {
                "description": "Book object that needs to be added to the body",
                "required": true,
                "content": {
                    "application/json": {
                        "schema": {},
                        "example": {
                            "author_id": 2,
                            "title": "Kung Fu Boy"
                        }
                    }
                }
            }
        }
    }
}
